/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../sanity.schema.json
export type MonthlyPassCard = {
  _id: string;
  _type: "monthlyPassCard";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalKey?: Slug;
  name?: LocalizedString;
  priceCents?: number;
  validityMonths?: number;
  accessType?: "limited" | "unlimited";
  sessions?: number;
  checkoutUrl?: string;
  verifiedAt?: string;
  order?: number;
  active?: boolean;
  editorialState?: "draft" | "review" | "ready";
};

export type LocalizedString = {
  _type: "localizedString";
  de?: string;
  en?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type MembershipCard = {
  _id: string;
  _type: "membershipCard";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalKey?: Slug;
  name?: LocalizedString;
  audience?: "adult" | "student" | "kid";
  monthlyPriceCents?: number;
  durationMonths?: 3 | 6 | 12 | 24;
  accessType?: "limited" | "unlimited";
  monthlySessions?: number;
  benefits?: Array<
    "muayThai" | "openGym" | "yoga" | "strengthConditioning" | "mobility"
  >;
  checkoutUrl?: string;
  verifiedAt?: string;
  order?: number;
  active?: boolean;
  editorialState?: "draft" | "review" | "ready";
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalKey?: Slug;
  question?: LocalizedString;
  answer?: LocalizedRichText;
  category?:
    "gettingStarted" | "equipment" | "training" | "memberships" | "other";
  order?: number;
  active?: boolean;
  editorialState?: "draft" | "review" | "ready";
};

export type LocalizedRichText = {
  _type: "localizedRichText";
  de?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  en?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Coach = {
  _id: string;
  _type: "coach";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalKey?: Slug;
  name?: string;
  role?: LocalizedString;
  photo?: EditorialImage;
  biography?: LocalizedRichText;
  specialties?: Array<
    {
      _key: string;
    } & LocalizedString
  >;
  socialUrl?: string;
  order?: number;
  active?: boolean;
  editorialState?: "draft" | "review" | "ready";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type EditorialImage = {
  _type: "editorialImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  decorative?: boolean;
  alternativeText?: LocalizedAlternativeText;
  caption?: LocalizedString;
  source?: string;
  rightsHolder?: string;
  rightsStatus?: "pending" | "approved";
  peopleConsent?: "notApplicable" | "confirmed" | "pending";
};

export type ClassType = {
  _id: string;
  _type: "classType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalKey?: Slug;
  name?: LocalizedString;
  summary?: LocalizedText;
  description?: LocalizedRichText;
  level?:
    | "beginners"
    | "intermediate"
    | "allLevels"
    | "advanced"
    | "fighters"
    | "children"
    | "private";
  durationMinutes?: number;
  audience?: LocalizedText;
  equipment?: Array<
    {
      _key: string;
    } & LocalizedString
  >;
  image?: EditorialImage;
  ctaLabel?: LocalizedString;
  order?: number;
  active?: boolean;
  editorialState?: "draft" | "review" | "ready";
};

export type LocalizedText = {
  _type: "localizedText";
  de?: string;
  en?: string;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: LocalizedString;
  heroTitlePrimary?: LocalizedString;
  heroTitleSecondary?: LocalizedString;
  heroIntroduction?: LocalizedText;
  heroImage?: EditorialImage;
  storyHeading?: LocalizedString;
  chapters?: Array<
    {
      _key: string;
    } & AboutChapter
  >;
  philosophyTitle?: LocalizedString;
  philosophyValues?: Array<
    {
      _key: string;
    } & PhilosophyValue
  >;
  seo?: SeoMetadata;
  editorialState?: "draft" | "review" | "ready";
};

export type SeoMetadata = {
  _type: "seoMetadata";
  title?: LocalizedString;
  description?: LocalizedText;
  shareImage?: EditorialImage;
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: LocalizedString;
  heroTitleLines?: Array<
    {
      _key: string;
    } & LocalizedString
  >;
  heroIntroduction?: LocalizedText;
  heroImage?: EditorialImage;
  trialActionLabel?: LocalizedString;
  scheduleActionLabel?: LocalizedString;
  valuesEyebrow?: LocalizedString;
  valuesTitle?: LocalizedString;
  valuesTitleAccent?: LocalizedString;
  valuesIntroduction?: LocalizedText;
  features?: Array<
    {
      _key: string;
    } & HomepageFeature
  >;
  seo?: SeoMetadata;
  editorialState?: "draft" | "review" | "ready";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  gymName?: LocalizedString;
  footerStatement?: LocalizedText;
  contactStatus?: "placeholder" | "verified";
  address?: PostalAddress;
  email?: string;
  telephone?: string;
  openingHours?: Array<
    {
      _key: string;
    } & OpeningHoursEntry
  >;
  instagramUrl?: string;
  instagramHandle?: string;
  defaultSeo?: SeoMetadata;
  editorialState?: "draft" | "review" | "ready";
};

export type PostalAddress = {
  _type: "postalAddress";
  lines?: Array<string>;
  mapUrl?: string;
};

export type PhilosophyValue = {
  _type: "philosophyValue";
  internalKey?: "technique" | "discipline" | "respect" | "community";
  title?: LocalizedString;
  description?: LocalizedText;
};

export type AboutChapter = {
  _type: "aboutChapter";
  internalKey?:
    "kruTiger" | "rootsThailand" | "ringExperience" | "thailandToBerlin";
  title?: LocalizedString;
  description?: LocalizedText;
  accent?: LocalizedString;
  primaryImage?: EditorialImage;
  secondaryImage?: EditorialImage;
};

export type HomepageFeature = {
  _type: "homepageFeature";
  internalKey?:
    "authenticity" | "allLevels" | "community" | "experiencedCoaches";
  title?: LocalizedString;
  description?: LocalizedText;
};

export type OpeningHoursEntry = {
  _type: "openingHoursEntry";
  days?: LocalizedString;
  hours?: LocalizedString;
};

export type LocalizedAlternativeText = {
  _type: "localizedAlternativeText";
  de?: string;
  en?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | MonthlyPassCard
  | LocalizedString
  | Slug
  | MembershipCard
  | Faq
  | LocalizedRichText
  | Coach
  | SanityImageAssetReference
  | EditorialImage
  | ClassType
  | LocalizedText
  | AboutPage
  | SeoMetadata
  | Homepage
  | SiteSettings
  | PostalAddress
  | PhilosophyValue
  | AboutChapter
  | HomepageFeature
  | OpeningHoursEntry
  | LocalizedAlternativeText
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"] | order(_updatedAt desc)[0] {    _id,    gymName,    footerStatement,    contactStatus,    address,    email,    telephone,    openingHours,    instagramUrl,    instagramHandle,    defaultSeo {      title,      description,      shareImage {        asset,        crop,        hotspot,        decorative,        alternativeText,        caption      }    }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: string;
  gymName: LocalizedString | null;
  footerStatement: LocalizedText | null;
  contactStatus: "placeholder" | "verified" | null;
  address: PostalAddress | null;
  email: string | null;
  telephone: string | null;
  openingHours: Array<
    {
      _key: string;
    } & OpeningHoursEntry
  > | null;
  instagramUrl: string | null;
  instagramHandle: string | null;
  defaultSeo: {
    title: LocalizedString | null;
    description: LocalizedText | null;
    shareImage: {
      asset: SanityImageAssetReference | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      decorative: boolean | null;
      alternativeText: LocalizedAlternativeText | null;
      caption: LocalizedString | null;
    } | null;
  } | null;
} | null;

// Source: ../src/lib/sanity/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "homepage"] | order(_updatedAt desc)[0] {    _id,    heroEyebrow,    heroTitleLines,    heroIntroduction,    heroImage {      asset,      crop,      hotspot,      decorative,      alternativeText,      caption    },    trialActionLabel,    scheduleActionLabel,    valuesEyebrow,    valuesTitle,    valuesTitleAccent,    valuesIntroduction,    features[] {      internalKey,      title,      description    },    seo {      title,      description,      shareImage {        asset,        crop,        hotspot,        decorative,        alternativeText,        caption      }    }  }
export type HOMEPAGE_QUERY_RESULT = {
  _id: string;
  heroEyebrow: LocalizedString | null;
  heroTitleLines: Array<
    {
      _key: string;
    } & LocalizedString
  > | null;
  heroIntroduction: LocalizedText | null;
  heroImage: {
    asset: SanityImageAssetReference | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    decorative: boolean | null;
    alternativeText: LocalizedAlternativeText | null;
    caption: LocalizedString | null;
  } | null;
  trialActionLabel: LocalizedString | null;
  scheduleActionLabel: LocalizedString | null;
  valuesEyebrow: LocalizedString | null;
  valuesTitle: LocalizedString | null;
  valuesTitleAccent: LocalizedString | null;
  valuesIntroduction: LocalizedText | null;
  features: Array<{
    internalKey:
      "allLevels" | "authenticity" | "community" | "experiencedCoaches" | null;
    title: LocalizedString | null;
    description: LocalizedText | null;
  }> | null;
  seo: {
    title: LocalizedString | null;
    description: LocalizedText | null;
    shareImage: {
      asset: SanityImageAssetReference | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      decorative: boolean | null;
      alternativeText: LocalizedAlternativeText | null;
      caption: LocalizedString | null;
    } | null;
  } | null;
} | null;

// Source: ../src/lib/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage"] | order(_updatedAt desc)[0] {    _id,    heroEyebrow,    heroTitlePrimary,    heroTitleSecondary,    heroIntroduction,    heroImage {      asset,      crop,      hotspot,      decorative,      alternativeText,      caption    },    storyHeading,    chapters[] {      internalKey,      title,      description,      accent,      primaryImage {        asset,        crop,        hotspot,        decorative,        alternativeText,        caption      },      secondaryImage {        asset,        crop,        hotspot,        decorative,        alternativeText,        caption      }    },    philosophyTitle,    philosophyValues[] {      internalKey,      title,      description    },    seo {      title,      description,      shareImage {        asset,        crop,        hotspot,        decorative,        alternativeText,        caption      }    }  }
export type ABOUT_PAGE_QUERY_RESULT = {
  _id: string;
  heroEyebrow: LocalizedString | null;
  heroTitlePrimary: LocalizedString | null;
  heroTitleSecondary: LocalizedString | null;
  heroIntroduction: LocalizedText | null;
  heroImage: {
    asset: SanityImageAssetReference | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    decorative: boolean | null;
    alternativeText: LocalizedAlternativeText | null;
    caption: LocalizedString | null;
  } | null;
  storyHeading: LocalizedString | null;
  chapters: Array<{
    internalKey:
      | "kruTiger"
      | "ringExperience"
      | "rootsThailand"
      | "thailandToBerlin"
      | null;
    title: LocalizedString | null;
    description: LocalizedText | null;
    accent: LocalizedString | null;
    primaryImage: {
      asset: SanityImageAssetReference | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      decorative: boolean | null;
      alternativeText: LocalizedAlternativeText | null;
      caption: LocalizedString | null;
    } | null;
    secondaryImage: {
      asset: SanityImageAssetReference | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      decorative: boolean | null;
      alternativeText: LocalizedAlternativeText | null;
      caption: LocalizedString | null;
    } | null;
  }> | null;
  philosophyTitle: LocalizedString | null;
  philosophyValues: Array<{
    internalKey: "community" | "discipline" | "respect" | "technique" | null;
    title: LocalizedString | null;
    description: LocalizedText | null;
  }> | null;
  seo: {
    title: LocalizedString | null;
    description: LocalizedText | null;
    shareImage: {
      asset: SanityImageAssetReference | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      decorative: boolean | null;
      alternativeText: LocalizedAlternativeText | null;
      caption: LocalizedString | null;
    } | null;
  } | null;
} | null;

// Source: ../src/lib/sanity/queries.ts
// Variable: TRAINING_CLASSES_QUERY
// Query: *[_type == "classType" && active == true]    | order(order asc, name.de asc, internalKey.current asc) {      _id,      "internalKey": internalKey.current,      name,      summary,      description,      level,      durationMinutes,      audience,      equipment,      image {        asset,        crop,        hotspot,        decorative,        alternativeText,        caption      },      ctaLabel,      order    }
export type TRAINING_CLASSES_QUERY_RESULT = Array<{
  _id: string;
  internalKey: string | null;
  name: LocalizedString | null;
  summary: LocalizedText | null;
  description: LocalizedRichText | null;
  level:
    | "advanced"
    | "allLevels"
    | "beginners"
    | "children"
    | "fighters"
    | "intermediate"
    | "private"
    | null;
  durationMinutes: number | null;
  audience: LocalizedText | null;
  equipment: Array<
    {
      _key: string;
    } & LocalizedString
  > | null;
  image: {
    asset: SanityImageAssetReference | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    decorative: boolean | null;
    alternativeText: LocalizedAlternativeText | null;
    caption: LocalizedString | null;
  } | null;
  ctaLabel: LocalizedString | null;
  order: number | null;
}>;

// Source: ../src/lib/sanity/queries.ts
// Variable: COACHES_QUERY
// Query: *[_type == "coach" && active == true]    | order(order asc, name asc, internalKey.current asc) {      _id,      "internalKey": internalKey.current,      name,      role,      photo {        asset,        crop,        hotspot,        decorative,        alternativeText,        caption      },      biography,      specialties,      socialUrl,      order    }
export type COACHES_QUERY_RESULT = Array<{
  _id: string;
  internalKey: string | null;
  name: string | null;
  role: LocalizedString | null;
  photo: {
    asset: SanityImageAssetReference | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    decorative: boolean | null;
    alternativeText: LocalizedAlternativeText | null;
    caption: LocalizedString | null;
  } | null;
  biography: LocalizedRichText | null;
  specialties: Array<
    {
      _key: string;
    } & LocalizedString
  > | null;
  socialUrl: string | null;
  order: number | null;
}>;

// Source: ../src/lib/sanity/queries.ts
// Variable: FAQS_QUERY
// Query: *[_type == "faq" && active == true]    | order(order asc, question.de asc, internalKey.current asc) {      _id,      "internalKey": internalKey.current,      question,      answer,      category,      order    }
export type FAQS_QUERY_RESULT = Array<{
  _id: string;
  internalKey: string | null;
  question: LocalizedString | null;
  answer: LocalizedRichText | null;
  category:
    | "equipment"
    | "gettingStarted"
    | "memberships"
    | "other"
    | "training"
    | null;
  order: number | null;
}>;

// Source: ../src/lib/sanity/queries.ts
// Variable: MEMBERSHIP_CARDS_QUERY
// Query: *[_type == "membershipCard" && active == true]    | order(audience asc, durationMonths desc, order asc, name.de asc, internalKey.current asc) {      _id,      "internalKey": internalKey.current,      name,      audience,      monthlyPriceCents,      durationMonths,      accessType,      monthlySessions,      benefits,      checkoutUrl,      verifiedAt,      order    }
export type MEMBERSHIP_CARDS_QUERY_RESULT = Array<{
  _id: string;
  internalKey: string | null;
  name: LocalizedString | null;
  audience: "adult" | "kid" | "student" | null;
  monthlyPriceCents: number | null;
  durationMonths: 12 | 24 | 3 | 6 | null;
  accessType: "limited" | "unlimited" | null;
  monthlySessions: number | null;
  benefits: Array<
    "mobility" | "muayThai" | "openGym" | "strengthConditioning" | "yoga"
  > | null;
  checkoutUrl: string | null;
  verifiedAt: string | null;
  order: number | null;
}>;

// Source: ../src/lib/sanity/queries.ts
// Variable: MONTHLY_PASS_CARDS_QUERY
// Query: *[_type == "monthlyPassCard" && active == true]    | order(order asc, name.de asc, internalKey.current asc) {      _id,      "internalKey": internalKey.current,      name,      priceCents,      validityMonths,      accessType,      sessions,      checkoutUrl,      verifiedAt,      order    }
export type MONTHLY_PASS_CARDS_QUERY_RESULT = Array<{
  _id: string;
  internalKey: string | null;
  name: LocalizedString | null;
  priceCents: number | null;
  validityMonths: number | null;
  accessType: "limited" | "unlimited" | null;
  sessions: number | null;
  checkoutUrl: string | null;
  verifiedAt: string | null;
  order: number | null;
}>;

// Source: ../src/lib/sanity/queries.ts
// Variable: SEO_CONTENT_QUERY
// Query: {    "default": *[_type == "siteSettings"] | order(_updatedAt desc)[0].defaultSeo {      title,      description,      shareImage {        asset,        crop,        hotspot,        decorative,        alternativeText,        caption      }    },    "homepage": *[_type == "homepage"] | order(_updatedAt desc)[0].seo {      title,      description,      shareImage {        asset,        crop,        hotspot,        decorative,        alternativeText,        caption      }    },    "about": *[_type == "aboutPage"] | order(_updatedAt desc)[0].seo {      title,      description,      shareImage {        asset,        crop,        hotspot,        decorative,        alternativeText,        caption      }    }  }
export type SEO_CONTENT_QUERY_RESULT = {
  default: {
    title: LocalizedString | null;
    description: LocalizedText | null;
    shareImage: {
      asset: SanityImageAssetReference | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      decorative: boolean | null;
      alternativeText: LocalizedAlternativeText | null;
      caption: LocalizedString | null;
    } | null;
  } | null;
  homepage: {
    title: LocalizedString | null;
    description: LocalizedText | null;
    shareImage: {
      asset: SanityImageAssetReference | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      decorative: boolean | null;
      alternativeText: LocalizedAlternativeText | null;
      caption: LocalizedString | null;
    } | null;
  } | null;
  about: {
    title: LocalizedString | null;
    description: LocalizedText | null;
    shareImage: {
      asset: SanityImageAssetReference | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      decorative: boolean | null;
      alternativeText: LocalizedAlternativeText | null;
      caption: LocalizedString | null;
    } | null;
  } | null;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"] | order(_updatedAt desc)[0] {\n    _id,\n    gymName,\n    footerStatement,\n    contactStatus,\n    address,\n    email,\n    telephone,\n    openingHours,\n    instagramUrl,\n    instagramHandle,\n    defaultSeo {\n      title,\n      description,\n      shareImage {\n        asset,\n        crop,\n        hotspot,\n        decorative,\n        alternativeText,\n        caption\n      }\n    }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "homepage"] | order(_updatedAt desc)[0] {\n    _id,\n    heroEyebrow,\n    heroTitleLines,\n    heroIntroduction,\n    heroImage {\n      asset,\n      crop,\n      hotspot,\n      decorative,\n      alternativeText,\n      caption\n    },\n    trialActionLabel,\n    scheduleActionLabel,\n    valuesEyebrow,\n    valuesTitle,\n    valuesTitleAccent,\n    valuesIntroduction,\n    features[] {\n      internalKey,\n      title,\n      description\n    },\n    seo {\n      title,\n      description,\n      shareImage {\n        asset,\n        crop,\n        hotspot,\n        decorative,\n        alternativeText,\n        caption\n      }\n    }\n  }\n': HOMEPAGE_QUERY_RESULT;
    '\n  *[_type == "aboutPage"] | order(_updatedAt desc)[0] {\n    _id,\n    heroEyebrow,\n    heroTitlePrimary,\n    heroTitleSecondary,\n    heroIntroduction,\n    heroImage {\n      asset,\n      crop,\n      hotspot,\n      decorative,\n      alternativeText,\n      caption\n    },\n    storyHeading,\n    chapters[] {\n      internalKey,\n      title,\n      description,\n      accent,\n      primaryImage {\n        asset,\n        crop,\n        hotspot,\n        decorative,\n        alternativeText,\n        caption\n      },\n      secondaryImage {\n        asset,\n        crop,\n        hotspot,\n        decorative,\n        alternativeText,\n        caption\n      }\n    },\n    philosophyTitle,\n    philosophyValues[] {\n      internalKey,\n      title,\n      description\n    },\n    seo {\n      title,\n      description,\n      shareImage {\n        asset,\n        crop,\n        hotspot,\n        decorative,\n        alternativeText,\n        caption\n      }\n    }\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '\n  *[_type == "classType" && active == true]\n    | order(order asc, name.de asc, internalKey.current asc) {\n      _id,\n      "internalKey": internalKey.current,\n      name,\n      summary,\n      description,\n      level,\n      durationMinutes,\n      audience,\n      equipment,\n      image {\n        asset,\n        crop,\n        hotspot,\n        decorative,\n        alternativeText,\n        caption\n      },\n      ctaLabel,\n      order\n    }\n': TRAINING_CLASSES_QUERY_RESULT;
    '\n  *[_type == "coach" && active == true]\n    | order(order asc, name asc, internalKey.current asc) {\n      _id,\n      "internalKey": internalKey.current,\n      name,\n      role,\n      photo {\n        asset,\n        crop,\n        hotspot,\n        decorative,\n        alternativeText,\n        caption\n      },\n      biography,\n      specialties,\n      socialUrl,\n      order\n    }\n': COACHES_QUERY_RESULT;
    '\n  *[_type == "faq" && active == true]\n    | order(order asc, question.de asc, internalKey.current asc) {\n      _id,\n      "internalKey": internalKey.current,\n      question,\n      answer,\n      category,\n      order\n    }\n': FAQS_QUERY_RESULT;
    '\n  *[_type == "membershipCard" && active == true]\n    | order(audience asc, durationMonths desc, order asc, name.de asc, internalKey.current asc) {\n      _id,\n      "internalKey": internalKey.current,\n      name,\n      audience,\n      monthlyPriceCents,\n      durationMonths,\n      accessType,\n      monthlySessions,\n      benefits,\n      checkoutUrl,\n      verifiedAt,\n      order\n    }\n': MEMBERSHIP_CARDS_QUERY_RESULT;
    '\n  *[_type == "monthlyPassCard" && active == true]\n    | order(order asc, name.de asc, internalKey.current asc) {\n      _id,\n      "internalKey": internalKey.current,\n      name,\n      priceCents,\n      validityMonths,\n      accessType,\n      sessions,\n      checkoutUrl,\n      verifiedAt,\n      order\n    }\n': MONTHLY_PASS_CARDS_QUERY_RESULT;
    '\n  {\n    "default": *[_type == "siteSettings"] | order(_updatedAt desc)[0].defaultSeo {\n      title,\n      description,\n      shareImage {\n        asset,\n        crop,\n        hotspot,\n        decorative,\n        alternativeText,\n        caption\n      }\n    },\n    "homepage": *[_type == "homepage"] | order(_updatedAt desc)[0].seo {\n      title,\n      description,\n      shareImage {\n        asset,\n        crop,\n        hotspot,\n        decorative,\n        alternativeText,\n        caption\n      }\n    },\n    "about": *[_type == "aboutPage"] | order(_updatedAt desc)[0].seo {\n      title,\n      description,\n      shareImage {\n        asset,\n        crop,\n        hotspot,\n        decorative,\n        alternativeText,\n        caption\n      }\n    }\n  }\n': SEO_CONTENT_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
